dist: bionic
language: java
jdk: openjdk8

before_install:
  - git clone https://github.com/GNS-Science/opensha-commons.git $TRAVIS_BUILD_DIR/../opensha-commons
  - git clone https://github.com/opensha/opensha-core.git $TRAVIS_BUILD_DIR/../opensha-core
  - git clone --branch=sliprate_uncertainty_constraint https://github.com/GNS-Science/opensha-ucerf3.git $TRAVIS_BUILD_DIR/../opensha-ucerf3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check -x test
  - ./gradlew localTests integrationTest
